vaadin.launch-browser=true
spring.application.name=libretago

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.devtools.restart.poll-interval=2000ms
spring.devtools.restart.quiet-period=1000ms

spring.jpa.show-sql=true

app.firebase.configuration.file=${FIREBASE_CONFIG_FILE}
